name: "Terraform Pipeline v1"
on:
  push:
    branches:
      - main

jobs:
 
  terraform-apply:
    name: "Apply Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
        with:
          ref: main        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false
          
      - name: Terraform Init
        id: init1
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.AZURE_BACKEND_KEY }}" 

      - name: Terraform Apply
        id: apply1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -no-color -input=false
        env:
          VES_P12_PASSWORD: ${{ secrets.VES_P12_PASSWORD }}
          # TF_LOG: debug 